In [1]:
import pandas as pd
from table_utils import axis_value_counts_table

session_mapping = pd.read_json("../data/core/session_mapping.json")
annotated_misalignments = pd.read_json("../data/core/annotated_misalignments.json")

In [2]:
axis_value_counts_table(
    session_mapping[session_mapping["source"] == "swe"],
    "license_type",
    include_session_type_pct=False,
).sort_values("count", ascending=False)

                     count percent
MIT                   4098  70.84%
AGPL-3.0               675  11.67%
Apache-2.0             603  10.42%
GPL-3.0                221   3.82%
ISC                    111   1.92%
FSL-1.1-Apache-2.0      26   0.45%
WTFPL                   22   0.38%
Elastic License 2.0      9   0.16%
MIT-0                    7   0.12%
GPL-3.0-or-later         5   0.09%
BSD-2-Clause             3   0.05%
CC0-1.0                  3   0.05%
FSL-1.1-ALv2             1   0.02%
O'Saasy                  1   0.02%

In [3]:
axis_value_counts_table(
    session_mapping[session_mapping["source"] == "specstory"],
    "license_type",
    include_session_type_pct=False,
).sort_values("count", ascending=False)

              count percent
NO_LICENSE     8971  60.66%
MIT            3585  24.24%
NOASSERTION     913   6.17%
Apache-2.0      413   2.79%
GPL-3.0         408   2.76%
BSD-2-Clause    343   2.32%
ISC              63   0.43%
LGPL-2.1         24   0.16%
MPL-2.0          19   0.13%
BSD-3-Clause     12   0.08%
CC-BY-4.0        10   0.07%
AGPL-3.0          9   0.06%
GPL-2.0           8   0.05%
LGPL-3.0          7   0.05%
CC-BY-SA-4.0      4   0.03%

In [4]:
axis_value_counts_table(
    annotated_misalignments[annotated_misalignments["source"] == "specstory"],
    "license_type",
    include_session_type_pct=False,
).sort_values("count", ascending=False)

              count percent
NO_LICENSE     7803   64.5%
MIT            2952   24.4%
NOASSERTION     555   4.59%
GPL-3.0         282   2.33%
Apache-2.0      263   2.17%
BSD-2-Clause    161   1.33%
ISC              38   0.31%
MPL-2.0          14   0.12%
LGPL-3.0         10   0.08%
BSD-3-Clause      8   0.07%
LGPL-2.1          8   0.07%
CC-BY-4.0         3   0.02%
AGPL-3.0          1   0.01%